---
- name: SNOW - Create an incident
  hosts: localhost
  connection: local
  gather_facts: false
    
  vars:
    sn_username: "{{ lookup('ansible.builtin.env', 'SN_USERNAME') }}"
    sn_instance: "{{ lookup('ansible.builtin.env', 'SN_HOST') }}"

  tasks: 

    - name: Create an Incident ticket on SNOW from an EDA Event from Instana
      servicenow.itsm.incident:
        state: new
        description: |
          "EDA Event from Instana - {{ problemText }} on {{ instance_id }}. {{ fix_suggestion }}. {{ explanation }}."
        short_description: "Instana Alert on {{ instance_fqdn }} - {{ instance_id }}"
        caller: "{{ sn_username }}"
        urgency: "low"
        impact: "low"
      register: snow_incident

    - name: Display new SNOW Incident number
      ansible.builtin.debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"
