---
- name: Basic Webhook Actions Test
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001


  rules:
    - name: EDA - Basic Webhook Testing from EDA to AAP
      condition: event.payload.catalog_item == "Norville - SNOW AAP EDA Cool Stuff"
      action:
        run_job_template:
          name: 'EDA - Basic Test'
          organization: 'Default'

    - name: EDA - Kick off a JCL Job on a Z/OS System
      condition: event.payload.catalog_item == "Norville - SNOW EDA AAP JCL ZOS"
      action:
        run_job_template:
          name: 'Z/OS - Submit a Job and update SNOW Ticket'
          organization: 'Vandelay Industries'

    
