---
- name: Listen for events from Instana
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000


 ## Define the conditions we are looking for

  rules:

    - name: Event
      condition: event.payload.problem.problem_text == "System load too high"
      action:
        run_job_template:
          name: 'SNOW - Instana Event'
          organization: 'Default'
          job_args:
            extra_vars:
              problemText: "{{ event['payload']['problem']['problem_text'] }}"
              explanation: "{{ event['payload']['problem']['explanation'] }}"
              fix_suggestion: "{{ event['payload']['problem']['fix_suggestion'] }}"
              instance_id: "{{ event['payload']['problem']['host_id'] }}"
              instance_fqdn: "{{ event['payload']['metadata']['fqdn'] }}"
